### ISSUE TITLE
Dynamic configuration of markers and marker boards

### ISSUE THREAD

**Issue by raultron** [Sahloul/ar_sys#11]
Hi,

We are working with a system that requires to dynamically select which markers are going to be detected by the ar_sys package, for that we need to load the marker configuration online during execution and not at the launch of the node with parameters. 

We have a forked ar_sys version that implements this in a rough way using ros services and I would like to know if it is interesting for you to have it in the main repository. If so, we can clean the contribution and do a pull request.

cheers.

**Comment by Sahloul** [comment]
@raultron Sure thing, appreciated! Moreover, I would like to kindly ask you to maintain the package and its release repository since I am not unable to do so recently. Can you help?
