### ISSUE TITLE
Pose and Position does not return

### ISSUE THREAD

**Issue by ItzMeJP** [Sahloul/ar_sys#4]
I successfully start my launch, but when I put the markers in front of the camera the topics /ar_multi_boards/pose and /ar_multi_boards/position does not return nothing. Next my launch file.

![captura de tela de 2015-08-04 11 36 23](https://cloud.githubusercontent.com/assets/13644313/9063302/1d0c8286-3a9d-11e5-871f-ccc28be3ac73.png)

I did the calibration of my camera but in terminal the fallow error appears:
[ERROR] [1438699028.768767000]: Rectified topic '/camera1/image_rect_color' requested but camera publishing '/camera1/camera_info' is uncalibrated

There is something that I missing?

**Comment by raultron** [comment]
I think maybe you have a problem with the image_proc part, or maybe your camera calibration file is not available. Check if the following command publishes a rectified image:

ROS_NAMESPACE=/camera1 rosrun image_proc image_proc

**Comment by Sahloul** [comment]
@ItzMeJP, could you confirm what are the results of the test suggested by raultron above?

**Comment by ItzMeJP** [comment]
The problem has been solved.
The error was the calibration. The style of calibration using D,K,R and P parameters are only for usb_cam drivers. However usb_cam drivers package is not usefull on Ros Indigo. I don't know why, in the ar_track_alvar package I had the same issue with the usb_cam_driver on Indigo.

Using uvc_camera this problem was solved, but it's necessary to pass as parameter the config.yaml file with the calibration parameters.

Next the launch file that is working: 


![launch](https://cloud.githubusercontent.com/assets/13644313/9821753/b580774e-5892-11e5-81dd-9a322d7d3809.png)


Thanks.

**Comment by Sahloul** [comment]
Glad to hear that!
