### ISSUE TITLE
Question NOT ISSUE!

### ISSUE THREAD

**Issue by End-Effector** [Sahloul/ar_sys#7]
Hello people who made this fantastic package,

I'm a student working with your Aruco lib. I'm using it with ROS and I have 2 questions for you:

1) Why are the Aruco giving more error when the Aruco is straight to the camera? When the Aruco is in an angle I seem to get better results, there is less error in the poses.

2) I tried the Aruco with Gazebo and I was getting really high error in the poses, now that I'm working with actual robots and with Kinects and I get almost no error in the measurements of the Aruco poses. They are almost perfect, like 1 degrees of error, comparing to the almost ~10degree error in the Gazebo simulator. Any ideas why this happens?

Great job with the Aruco project was so helpful, thx you so much.

**Comment by Sahloul** [comment]
Hi @End-Effector, as you can see, we just developed a ROS wrapper of ArUco system.
I am not sure if your first question has any relation with [this issue](https://github.com/Sahloul/ar_sys/issues/5) or not, but apparently the authors of [ArUco library](http://www.uco.es/investiga/grupos/ava/node/26) could provide satisfying answers.
